### ISSUE TITLE
 datetime_ist = datetime.now(IST) AttributeError: module 'datetime' has no attribute 'now'

### ISSUE THREAD

**Issue by hruthik23** [adityap27/face-mask-detector#3]
Hello friend I have created my own face mask detector app using tensorflow, keras and openCV. However I am trying to implement an alert system in which it will send an alert message to the user. I tried to use your method however I am getting AttributeError: module 'datetime' has no attribute 'now' error. Can you please help me out?

**Comment by adityap27** [comment]
Hi @hruthik23 ,
make sure you are importing it in a right way.

`from datetime import datetime `

**Comment by hruthik23** [comment]
Hello I have managed to slove the error but I don't receive any message. I have changed my location to Singapore but still no message. I works for a while and then suddenly gives the same error again.

**Comment by adityap27** [comment]
Hi, @hruthik23 
This won't work for you. For SMS you will require API key which is a paid service.
I would rather suggest you to check sending emails via python to server your notification purpose.
You can also look for any other notification method that suits you.

**Comment by adityap27** [comment]
Closing this issue, **feel free to re-open** if you need help.
