### ISSUE TITLE
arguments are required: -y/--yolo

### ISSUE THREAD

**Issue by nanoakhi** [adityap27/face-mask-detector#4]
usage: mask-detector-video.py [-h] -y YOLO [-i INPUT] [-o OUTPUT] [-d DISPLAY]
                              [-c CONFIDENCE] [-t THRESHOLD] [-u USE_GPU]
mask-detector-video.py: error: the following arguments are required: -y/--yolo

Is there any help where i am wrong

**Comment by adityap27** [comment]
@nanoakhi 
-y is a required argument.
You can refer Quick Guide, to get the ideal command. 
Link : https://github.com/adityap27/face-mask-detector#Quick-Start

**Comment by nanoakhi** [comment]
Done successfully
